In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import numpy as np
# Sample scalar and array inputs
scalar = 3.7
arr = np.array([1, 2, 3, 4, 5, 6])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)
# Exponential and logarithm
exp_values = np.exp(arr)
log_values = np.log(arr)  # Natural logarithm

# Absolute value and square root
abs_values = np.abs(arr)
sqrt_values = np.sqrt(arr)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(arr, 2)

# Rounding functions
round_values = np.round(arr)
floor_values = np.floor(arr)
ceil_values = np.ceil(arr)

# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)
print("exp:", exp_values)
print("log:", log_values)
print("abs:", abs_values)
print("sqrt:", sqrt_values)
print("rem:", rem_values)
print("round:", round_values)
print("floor:", floor_values)
print("ceil:", ceil_values)


sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
tan: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]
asin: [0.16744808 0.33983691 0.52359878 0.72972766 0.98511078 1.57079633]
acos: [1.40334825 1.23095942 1.04719755 0.84106867 0.58568554 0.        ]
atan: [0.78539816 1.10714872 1.24904577 1.32581766 1.37340077 1.40564765]
exp: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
log: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
abs: [1 2 3 4 5 6]
sqrt: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
rem: [1 0 1 0 1 0]
round: [1 2 3 4 5 6]
floor: [1. 2. 3. 4. 5. 6.]
ceil: [1. 2. 3. 4. 5. 6.]


In [5]:
from sympy import Matrix
# Creating a 3x2 matrix
matrix = np.array([[1, 3], [2, 4], [6, 5]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[1 3]
 [2 4]
 [6 5]]

sin:
 [[ 0.84147098  0.14112001]
 [ 0.90929743 -0.7568025 ]
 [-0.2794155  -0.95892427]]

cos:
 [[ 0.54030231 -0.9899925 ]
 [-0.41614684 -0.65364362]
 [ 0.96017029  0.28366219]]

tan:
 [[ 1.55740772 -0.14254654]
 [-2.18503986  1.15782128]
 [-0.29100619 -3.38051501]]

asine:
 [[0.16744808 0.52359878]
 [0.33983691 0.72972766]
 [1.57079633 0.98511078]]

acosine:
 [[1.40334825 1.04719755]
 [1.23095942 0.84106867]
 [0.         0.58568554]]

atangent:
 [[0.78539816 1.24904577]
 [1.10714872 1.32581766]
 [1.40564765 1.37340077]]

exp:
 [[  2.71828183  20.08553692]
 [  7.3890561   54.59815003]
 [403.42879349 148.4131591 ]]

log (natural):
 [[0.         1.09861229]
 [0.69314718 1.38629436]
 [1.79175947 1.60943791]]

abs:
 [[1 3]
 [2 4]
 [6 5]]

sqrt:
 [[1.         1.73205081]
 [1.41421356 2.        ]
 [2.44948974 2.23606798]]

rem (remainder when divided by 2):
 [[1 1]
 [0 0]
 [0 1]]

round:
 [[1 3]
 [2 4]
 [6 5]]

floor:
 [[1. 3.]
 [2. 4.]
 [6. 5.]]

ceil:
 [[1. 3

In [6]:
import numpy as np

# Sample 2×3 matrix with float values
mat = np.array([
    [2.1, 4.7, 1.5],
    [8.3, 3.9, 6.2]
])

# 1. Maximum value and index
max_value = np.max(mat)
max_index = np.unravel_index(np.argmax(mat), mat.shape)

# 2. Minimum value and index
min_value = np.min(mat)
min_index = np.unravel_index(np.argmin(mat), mat.shape)

# 3. Length of the matrix (largest dimension, similar to MATLAB length())
mat_length = max(mat.shape)

# 4. Sorting
# Row-wise descending
row_sorted_desc = np.sort(mat, axis=1)[:, ::-1]

# Entire matrix descending
entire_sorted_desc = np.sort(mat.flatten())[::-1]

# 5. Sum of elements
sum_values = np.sum(mat)

# 6. Product of elements
prod_values = np.prod(mat)

# 7. Median value
median_value = np.median(mat)

# 8. Mean value
mean_value = np.mean(mat)

# 9. Standard deviation
std_dev = np.std(mat)

# Display results
print("Matrix:")
print(mat)

print("\nMax value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)

print("\nLength of matrix:", mat_length)

print("\nRow-wise descending sort:")
print(row_sorted_desc)

print("\nEntire matrix descending:")
print(entire_sorted_desc)

print("\nSum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)

Matrix:
[[2.1 4.7 1.5]
 [8.3 3.9 6.2]]

Max value: 8.3 at index (np.int64(1), np.int64(0))
Min value: 1.5 at index (np.int64(0), np.int64(2))

Length of matrix: 3

Row-wise descending sort:
[[4.7 2.1 1.5]
 [8.3 6.2 3.9]]

Entire matrix descending:
[8.3 6.2 4.7 3.9 2.1 1.5]

Sum of elements: 26.7
Product of elements: 2971.2746700000002
Median value: 4.3
Mean value: 4.45
Standard deviation: 2.326478024826369
