Simulation and Modeling Lab
Course Code: CSE 413
Submitted By: Sumaiya Alam Erina

ID: 1100

Date of Submission: 10 August, 2026



## Step 1: Create My Personal Matrix

Student ID: 0432320005101100

d1 = Last digit of my student ID = 0

d2 = Second last digit of my student ID = 0

In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
import numpy as np

# Create matrix by student ID
d1 = 0  # Last digit of my ID
d2 = 0  # 2nd last digit of my ID

A = np.array([[d1 + 2, d2 + 1],
              [2 * d1, d2 + 2]])

print("Matrix A:\n", A)

Matrix A:
 [[2 1]
 [0 2]]


## Step 4: Re-analyze Matrix B

The same matrix properties are calculated for matrix B.


In [4]:
# 1. Shape of A matrix
shape_A = A.shape

# 2. Determinant of A matrix
det_A = np.linalg.det(A)

# 3. Rank of A matrix
rank_A = np.linalg.matrix_rank(A)

# 4. Eigenvalues and eigenvectors
eigenvalues_A, eigenvectors_A = np.linalg.eig(A)

# 5. Inverse of A matrix
if det_A != 0:
    inv_A = np.linalg.inv(A)
else:
    inv_A = "Matrix is singular, cannot compute inverse"

# Display results
print("Shape of A:", shape_A)
print("Determinant of A:", det_A)
print("Rank of A:", rank_A)
print("Eigenvalues of A:", eigenvalues_A)
print("Eigenvectors of A:\n", eigenvectors_A)
print("Inverse of A:\n", inv_A)

Shape of A: (2, 2)
Determinant of A: 4.0
Rank of A: 2
Eigenvalues of A: [2. 2.]
Eigenvectors of A:
 [[ 1.0000000e+00 -1.0000000e+00]
 [ 0.0000000e+00  4.4408921e-16]]
Inverse of A:
 [[ 0.5  -0.25]
 [ 0.    0.5 ]]


## Step 5: Comparison and Explanation

### 6. How did the determinant change and why?

The determinant of A was 4, while the determinant of B is 6.
Therefore, the determinant increased by 2. This happened because one element of matrix A was increased by 1, which changed the determinant calculation.

### 7. Did the rank change? Explain.

The rank of A is 2 and the rank of B is also 2.
Therefore, the rank did not change. Both matrices have full rank because both rows are linearly independent.

### 8. How did the eigenvalues respond to the value change?

The eigenvalues of A were 2 and 2, while the eigenvalues of B are 3 and 2.
Therefore, one of the eigenvalues changed from 2 to 3 after increasing one matrix element by 1.

### 9. Is B easier or harder to invert than A? Why?

Both A and B are invertible because their determinants are non-zero. The determinant of A is 4 and the determinant of B is 6. Therefore, neither matrix is singular, and the inverse of both matrices can be calculated.